# Generated by Django 6.0.4 on 2026-04-20 08:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_paper_created_at_paper_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reviewassignment',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='coauthor',
            constraint=models.UniqueConstraint(fields=('paper', 'user'), name='unique_user_per_paper'),
        ),
        migrations.AddConstraint(
            model_name='reviewassignment',
            constraint=models.UniqueConstraint(fields=('paper', 'reviewer'), name='unique_reviewer_per_paper'),
        ),
    ]
