# Generated by Django 6.0.4 on 2026-04-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_alter_reviewassignment_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='pdf',
            field=models.FileField(upload_to='paper/'),
        ),
    ]
