# Generated by Django 6.0.4 on 2026-04-18 09:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('short_name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('location', models.CharField(max_length=255)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('description', models.TextField(blank=True)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['start_date', 'end_date'], name='conferences_start_d_b18da9_idx')],
            },
        ),
    ]
