# Generated by Django 6.0.4 on 2026-04-18 11:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conferences', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('hero_badge', models.CharField(max_length=100)),
                ('hero_title', models.CharField(db_index=True, max_length=255)),
                ('hero_summary', models.TextField(blank=True, null=True)),
                ('conference', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='about_event', to='conferences.conference')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('year', models.PositiveIntegerField(db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(upload_to='archives/')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='conferences.conference')),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='CommitteeGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_groups', to='conferences.conference')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(blank=True, max_length=255)),
                ('affiliation', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='committee/')),
                ('order', models.IntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='cms.committeegroup')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('organization', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('cell', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('conference', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_info', to='conferences.conference')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('eyebrow', models.CharField(max_length=255)),
                ('pretitle', models.CharField(max_length=255)),
                ('title', models.TextField()),
                ('date_line', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True, null=True)),
                ('cta_primary_label', models.CharField(blank=True, max_length=100)),
                ('cta_primary_link', models.CharField(blank=True, max_length=255)),
                ('cta_secondary_label', models.CharField(blank=True, max_length=100)),
                ('cta_secondary_link', models.CharField(blank=True, max_length=255)),
                ('conference', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='conferences.conference')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HeroInfoCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('label', models.CharField(max_length=100)),
                ('text', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_cards', to='cms.herosection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ImportantDate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField(db_index=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='important_dates', to='conferences.conference')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='KeynoteSpeaker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('affiliation', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='keynotes/')),
                ('profile_url', models.URLField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keynote_speakers', to='conferences.conference')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('abstract_limit', models.PositiveIntegerField()),
                ('paper_limit', models.PositiveIntegerField()),
                ('review_type', models.CharField(choices=[('single_blind', 'Single Blind'), ('double_blind', 'Double Blind'), ('open', 'Open Review')], max_length=20)),
                ('language', models.CharField(choices=[('en', 'English'), ('bn', 'Bengali')], max_length=10)),
                ('conference', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission_config', to='conferences.conference')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TextItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('section', models.CharField(choices=[('submission', 'Submission'), ('full_paper', 'Full Paper'), ('proceedings', 'Proceedings')], db_index=True, max_length=100)),
                ('text', models.TextField()),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_items', to='cms.aboutevent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WelcomeSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('heading', models.CharField(max_length=255)),
                ('conference_name', models.TextField()),
                ('theme_title', models.CharField(max_length=255)),
                ('theme_intro', models.TextField()),
                ('scope_title', models.CharField(max_length=255)),
                ('abstract_note_title', models.CharField(max_length=255)),
                ('abstract_note', models.TextField()),
                ('conference', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='welcome_section', to='conferences.conference')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ThemeHighlight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('text', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('welcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='cms.welcomesection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ScopeArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('welcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='cms.welcomesection')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArchiveLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('label', models.CharField(blank='True', max_length=100)),
                ('url', models.URLField()),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='cms.archive')),
            ],
            options={
                'unique_together': {('archive', 'url')},
            },
        ),
        migrations.CreateModel(
            name='IndexingTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('label', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='indexing/')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indexings', to='cms.aboutevent')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('about', 'label'), name='unique_indexing_label_per_about')],
            },
        ),
        migrations.CreateModel(
            name='RegistrationFee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('category', models.CharField(db_index=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('BDT', 'BDT'), ('EUR', 'EUR')], max_length=3)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_fees', to='conferences.conference')),
            ],
            options={
                'ordering': ['amount'],
                'constraints': [models.UniqueConstraint(fields=('conference', 'category'), name='unique_fee_category_per_conference')],
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('label', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='sponsors/')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='cms.aboutevent')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('about', 'label'), name='unique_sponsor_per_about')],
            },
        ),
        migrations.CreateModel(
            name='VenueInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('label', models.CharField(max_length=100)),
                ('value', models.TextField()),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venues', to='cms.aboutevent')),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('about', 'label'), name='unique_venue_label_per_about')],
            },
        ),
    ]
