# Generated by Django 6.0.4 on 2026-04-18 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('about_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='herohighlights', to='cms.aboutevent')),
            ],
            options={
                'ordering': ['order'],
                'indexes': [models.Index(fields=['about_event', 'order'], name='cms_herohig_about_e_f5bac0_idx')],
            },
        ),
    ]
