# Generated by Django 6.0.4 on 2026-04-19 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_herohighlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='keynotespeaker',
            name='profileLabel',
            field=models.CharField(default='profile', max_length=30),
        ),
    ]
