# Generated by Django 6.0.4 on 2026-04-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_keynotespeaker_profilelabel'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutevent',
            name='contact_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='aboutevent',
            name='fees_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutevent',
            name='fees_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='aboutevent',
            name='full_paper_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='aboutevent',
            name='indexing_disclaimer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutevent',
            name='indexing_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='aboutevent',
            name='proceedings_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='aboutevent',
            name='sponsors_disclaimer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutevent',
            name='sponsors_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='aboutevent',
            name='submission_path_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='aboutevent',
            name='submission_process_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='aboutevent',
            name='timeline_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='aboutevent',
            name='venue_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='aboutevent',
            name='where_to_submit_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
