# Generated by Django 6.0.4 on 2026-04-19 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_aboutevent_contact_title_aboutevent_fees_summary_and_more'),
        ('conferences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='conference',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hero', to='conferences.conference'),
        ),
        migrations.AlterField(
            model_name='welcomesection',
            name='conference',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='welcome', to='conferences.conference'),
        ),
    ]
