# Generated by Django 6.0.4 on 2026-04-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_alter_herosection_conference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='cta_label',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
